
import AdminSidebar from "./_components/admin-sidebar"

export const metadata = {
  title: "Admin Dashboard | Equipment Daily Report",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="min-h-screen">
      <div className="flex min-h-screen overflow-hidden bg-[#F8F6F1]">
        <AdminSidebar />
        {children}
      </div>
    </div>
  );
}
