
export const metadata = {
  title: "Admin Dashboard | Equipment Daily Report",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      {children}
    </div>
  );
}
